### ISSUE TITLE
[FAQ] How to set application.yml?

### ISSUE THREAD

**Issue by jjyun-do** [S-ResearchStack/backend-system#4]
If Postgres is installed for the first time, you can set it to the values below.

```yaml
config:
  db:
    url: postgresql://localhost:5432/postgres
    host: localhost
    port: 5432
    name: postgres
    schema: default
    user: postgres
    password: VALUE // should be changed
  new-database-config:
    prefix: project_
    postfix: _research

logging:
  level:
    root: info

spring:
  flyway:
    url: jdbc:${config.db.url}
    user: ${config.db.user}
    password: ${config.db.password}

server:
  port: 3030
```
